/* DOTA JETCH — BRAIN RUS v1.0 */

var BrainRus = {
  slangToName: {
    "аега":"Aegis of the Immortal","аегис":"Aegis of the Immortal","эгида":"Aegis of the Immortal",
    "бкб":"Black King Bar","бкбшка":"Black King Bar","шива":"Shiva's Guard","шивка":"Shiva's Guard",
    "линка":"Linken's Sphere","манта":"Manta Style","бф":"Battle Fury","бабочка":"Butterfly",
    "мкб":"Monkey King Bar","дагон":"Dagon","дагонка":"Dagon","хекс":"Scythe of Vyse",
    "сатаник":"Satanic","дифуза":"Diffusal Blade","глиммер":"Glimmer Cape","форс":"Force Staff",
    "блинк":"Blink Dagger","бм":"Blade Mail","сапог":"Boots of Speed","бот":"Boots of Travel",
    "треды":"Power Treads","фаза":"Phase Boots","арканы":"Arcane Boots","танго":"Tango",
    "ванд":"Magic Wand","бутл":"Bottle","танк":"Vanguard","кримсон":"Crimson Guard",
    "пайп":"Pipe of Insight","мека":"Mekansm","грейвы":"Guardian Greaves","снж":"Sange and Yasha",
    "халберд":"Heaven's Halberd","атос":"Rod of Atos","глейпнир":"Gleipnir","орчид":"Orchid Malevolence",
    "блудорн":"Bloodthorn","эхо":"Echo Sabre","армлет":"Armlet of Mordiggian",
    "солярка":"Solar Crest","скеди":"Eye of Skadi","скади":"Eye of Skadi","сердце":"Heart of Tarrasque",
    "рад":"Radiance","радик":"Radiance","октарин":"Octarine Core","рефрешер":"Refresher Orb",
    "кровавик":"Bloodstone","эльда":"Aether Lens","эфирка":"Ethereal Blade","мир":"Wraith Band",
    "урна":"Urn of Shadows","сосуд":"Spirit Vessel","мидас":"Hand of Midas","мочка":"Mask of Madness",
    "морда":"Mask of Madness","маска":"Mask of Madness","дезоль":"Desolator","асу":"Assault Cuirass",
    "куйрас":"Assault Cuirass","ак":"Assault Cuirass","даедал":"Daedalus","мьёльнир":"Mjollnir",
    "маел":"Maelstrom","аеон":"Aeon Disk","аеонка":"Aeon Disk","пт":"Power Treads",
    "ам":"Anti-Mage","антимаг":"Anti-Mage","сф":"Shadow Fiend","па":"Phantom Assassin",
    "фантомка":"Phantom Assassin","пудж":"Pudge","мясник":"Pudge","инвокер":"Invoker",
    "вокер":"Invoker","жугер":"Juggernaut","джага":"Juggernaut","сларк":"Slark","рыба":"Slark",
    "шторм":"Storm Spirit","тини":"Tiny","камень":"Tiny","дров":"Drow Ranger","дровка":"Drow Ranger",
    "снайпер":"Sniper","свен":"Sven","рубик":"Rubick","магнус":"Magnus","маг":"Magnus",
    "тайдер":"Tidehunter","энigma":"Enigma","энигма":"Enigma","фурион":"Nature's Prophet",
    "фурик":"Nature's Prophet","нп":"Nature's Prophet","зевс":"Zeus","лина":"Lina",
    "кристалка":"Crystal Maiden","цм":"Crystal Maiden","цмка":"Crystal Maiden","лич":"Lich",
    "лайфстил":"Lifestealer","нага":"Naga Siren","виса":"Visage","визаж":"Visage",
    "дуза":"Medusa","медуза":"Medusa","горгона":"Medusa","мортра":"Phantom Assassin",
    "цк":"Chaos Knight","хк":"Chaos Knight","тимбер":"Timbersaw","тимберсо":"Timbersaw",
    "войд":"Faceless Void","спектра":"Spectre","спек":"Spectre","слардар":"Slardar","рики":"Riki",
    "фантом":"Phantom Lancer","пл":"Phantom Lancer","луна":"Luna","алхимик":"Alchemist","алх":"Alchemist",
    "кори":"Core","сап":"Support","сапорт":"Support","мид":"Mid Lane","сафе":"Safe Lane","офлейн":"Off Lane",
    "вижн":"Vision","вард":"Ward","обзор":"Observer Ward","сентри":"Sentry Ward","дуст":"Dust of Appearance",
    "смок":"Smoke of Deceit","рошан":"Roshan","роша":"Roshan","кс":"Kill Streak","тильт":"Tilt",
    "фид":"Feed","стак":"Stack","гпм":"GPM","хпм":"XPM","кда":"KDA","лх":"Last Hits","ластхит":"Last Hit",
    "денай":"Deny","гг":"Good Game","ульта":"Ultimate","улт":"Ultimate","кд":"Cooldown",
    "ммр":"MMR","птс":"MMR","ранкед":"Ranked","паб":"Public Match","лп":"Low Priority"
  },

  termTranslate: {
    "vision":"вижн","ward":"вард","observer ward":"обзорный вард","sentry ward":"сентри",
    "dust of appearance":"дуст","smoke of deceit":"смок","black king bar":"бкб",
    "linken's sphere":"линка","manta style":"манта","blink dagger":"блинк",
    "battle fury":"бф","butterfly":"бабочка","monkey king bar":"мкб",
    "scythe of vyse":"хекс","satanic":"сатаник","diffusal blade":"дифуза",
    "shiva's guard":"шива","rod of atos":"атос","orchid malevolence":"орчид"
