/* DOTA JETCH — BRAIN HEROES v1.0 */

var BRAIN_HEROES = [
  { id: 1, name: "Anti-Mage", attr: "agi", atk: "Melee", roles: ["Carry","Escape","Nuker"] },
  { id: 2, name: "Axe", attr: "str", atk: "Melee", roles: ["Initiator","Durable","Disabler","Carry"] },
  { id: 3, name: "Bane", attr: "all", atk: "Ranged", roles: ["Support","Disabler","Nuker","Durable"] },
  { id: 4, name: "Bloodseeker", attr: "agi", atk: "Melee", roles: ["Carry","Disabler","Nuker","Initiator"] },
  { id: 5, name: "Crystal Maiden", attr: "int", atk: "Ranged", roles: ["Support","Disabler","Nuker"] },
  { id: 6, name: "Drow Ranger", attr: "agi", atk: "Ranged", roles: ["Carry","Disabler","Pusher"] },
  { id: 7, name: "Earthshaker", attr: "str", atk: "Melee", roles: ["Support","Initiator","Disabler","Nuker"] },
  { id: 8, name: "Juggernaut", attr: "agi", atk: "Melee", roles: ["Carry","Pusher","Escape"] },
  { id: 9, name: "Mirana", attr: "agi", atk: "Ranged", roles: ["Carry","Support","Escape","Nuker","Disabler"] },
  { id: 10, name: "Morphling", attr: "agi", atk: "Ranged", roles: ["Carry","Escape","Durable","Nuker","Disabler"] },
  { id: 11, name: "Shadow Fiend", attr: "agi", atk: "Ranged", roles: ["Carry","Nuker"] },
  { id: 12, name: "Phantom Lancer", attr: "agi", atk: "Melee", roles: ["Carry","Escape","Pusher","Nuker"] },
  { id: 13, name: "Puck", attr: "int", atk: "Ranged", roles: ["Initiator","Disabler","Escape","Nuker"] },
  { id: 14, name: "Pudge", attr: "str", atk: "Melee", roles: ["Disabler","Initiator","Durable","Nuker"] },
  { id: 15, name: "Razor", attr: "agi", atk: "Ranged", roles: ["Carry","Durable","Nuker","Pusher"] },
  { id: 16, name: "Sand King", attr: "all", atk: "Melee", roles: ["Initiator","Disabler","Support","Nuker","Escape"] },
  { id: 17, name: "Storm Spirit", attr: "int", atk: "Ranged", roles: ["Carry","Escape","Nuker","Initiator","Disabler"] },
  { id: 18, name: "Sven", attr: "str", atk: "Melee", roles: ["Carry","Disabler","Initiator","Durable","Nuker"] },
  { id: 19, name: "Tiny", attr: "str", atk: "Melee", roles: ["Carry","Nuker","Pusher","Initiator","Durable","Disabler"] },
  { id: 20, name: "Vengeful Spirit", attr: "agi", atk: "Ranged", roles: ["Support","Initiator","Disabler","Nuker","Escape"] },
  { id: 21, name: "Windranger", attr: "all", atk: "Ranged", roles: ["Carry","Support","Disabler","Escape","Nuker"] },
  { id: 22, name: "Zeus", attr: "int", atk: "Ranged", roles: ["Nuker","Carry"] },
  { id: 23, name: "Kunkka", attr: "str", atk: "Melee", roles: ["Carry","Support","Disabler","Initiator","Durable","Nuker"] },
  { id: 25, name: "Lina", attr: "int", atk: "Ranged", roles: ["Support","Carry","Nuker","Disabler"] },
  { id: 26, name: "Lion", attr: "int", atk: "Ranged", roles: ["Support","Disabler","Nuker","Initiator"] },
  { id: 27, name: "Shadow Shaman", attr: "int", atk: "Ranged", roles: ["Support","Pusher","Disabler","Nuker","Initiator"] },
  { id: 28, name: "Slardar", attr: "str", atk: "Melee", roles: ["Carry","Durable","Initiator","Disabler","Escape"] },
  { id: 29, name: "Tidehunter", attr: "str", atk: "Melee", roles: ["Initiator","Durable","Disabler","Nuker","Carry"] },
  { id: 30, name: "Witch Doctor", attr: "int", atk: "Ranged", roles: ["Support","Nuker","Disabler"] },
  { id: 31, name: "Lich", attr: "int", atk: "Ranged", roles: ["Support","Nuker"] },
  { id: 32, name: "Riki", attr: "agi", atk: "Melee", roles: ["Carry","Escape","Disabler"] },
  { id: 33, name: "Enigma", attr: "all", atk: "Ranged", roles: ["Disabler","Initiator","Pusher"] },
  { id: 34, name: "Tinker", attr: "int", atk: "Ranged", roles: ["Carry","Nuker","Pusher"] },
  { id: 35, name: "Sniper", attr: "agi", atk: "Ranged", roles: ["Carry","Nuker"] },
  { id: 36, name: "Necrophos", attr: "int", atk: "Ranged", roles: ["Carry","Nuker","Durable","Disabler"] },
  { id: 37, name: "Warlock", attr: "int", atk: "Ranged", roles: ["Support","Initiator","Disabler"] },
  { id: 38, name: "Beastmaster", attr: "all", atk: "Melee", roles: ["Initiator","Disabler","Durable","Nuker"] },
  { id: 39, name: "Queen of Pain", attr: "int", atk: "Ranged", roles: ["Carry","Nuker","Escape"] },
  { id: 40, name: "Venomancer", attr: "all", atk: "Ranged", roles: ["Support","Nuker","Initiator","Pusher","Disabler"] },
  { id: 41, name: "Faceless Void", attr: "agi", atk: "Melee", roles: ["Carry","Initiator","Disabler","Escape","Durable"] },
  { id: 42, name: "Wraith King", attr: "str", atk: "Melee", roles: ["Carry","Support","Durable","Disabler","Initiator"] },
  { id: 43, name: "Death Prophet", attr: "all", atk: "Ranged", roles: ["Carry","Pusher","Nuker","Disabler"] },
  { id: 44, name: "Phantom Assassin", attr: "agi", atk: "Melee", roles: ["Carry","Escape"] },
  { id: 45, name: "Pugna", attr: "int", atk: "Ranged", roles: ["Nuker","Pusher"] },
  { id: 46, name: "Templar Assassin", attr: "agi", atk: "Ranged", roles: ["Carry","Escape"] },
  { id: 47, name: "Viper", attr: "agi", atk: "Ranged", roles: ["Carry","Durable","Initiator","Disabler"] },
  { id: 48, name: "Luna", attr: "agi", atk: "Ranged", roles: ["Carry","Nuker","Pusher"] },
  { id: 49, name: "Dragon Knight", attr: "str", atk: "Melee", roles: ["Carry","Pusher","Durable","Disabler","Initiator","Nuker"] },
  { id: 50, name: "Dazzle", attr: "all", atk: "Ranged", roles: ["Support","Nuker","Disabler"] },
  { id: 51, name: "Clockwerk", attr: "str", atk: "Melee", roles: ["Initiator","Disabler","Durable","Nuker"] },
  { id: 52, name: "Leshrac", attr: "int", atk: "Ranged", roles: ["Carry","Support","Nuker","Pusher","Disabler"] },
  { id: 53, name: "Nature's Prophet", attr: "all", atk: "Ranged", roles: ["Carry","Pusher","Escape","Nuker"] },
  { id: 54, name: "Lifestealer", attr: "str", atk: "Melee", roles: ["Carry","Durable","Escape","Disabler"] },
  { id: 55, name: "Dark Seer", attr: "int", atk: "Melee", roles: ["Initiator","Escape","Disabler"] },
  { id: 56, name: "Clinkz", attr: "agi", atk: "Ranged", roles: ["Carry","Escape","Pusher"] },
  { id: 57, name: "Omniknight", attr: "str", atk: "Melee", roles: ["Support","Durable","Nuker"] },
  { id: 58, name: "Enchantress", attr: "int", atk: "Ranged", roles: ["Support","Pusher","Durable","Disabler"] },
  { id: 59, name: "Huskar", attr: "str", atk: "Ranged", roles: ["Carry","Durable","Initiator"] },
  { id: 60, name: "Night Stalker", attr: "str", atk: "Melee", roles: ["Carry","Initiator","Durable","Disabler","Nuker"] },
  { id: 61, name: "Broodmother", attr: "agi", atk: "Melee", roles: ["Carry","Pusher","Escape","Nuker"] },
  { id: 62, name: "Bounty Hunter", attr: "agi", atk: "Melee", roles: ["Escape","Nuker"] },
  { id: 63, name: "Weaver", attr: "agi", atk: "Ranged", roles: ["Carry","Escape"] },
  { id: 64, name: "Jakiro", attr: "int", atk: "Ranged", roles: ["Support","Nuker","Pusher","Disabler"] },
  { id: 65, name: "Batrider", attr: "all", atk: "Ranged", roles: ["Initiator","Disabler","Escape"] },
  { id: 66, name: "Chen", attr: "int", atk: "Ranged", roles: ["Support","Pusher"] },
  { id: 67, name: "Spectre", attr: "agi", atk: "Melee", roles: ["Carry","Durable","Escape"] },
  { id: 68, name: "Ancient Apparition", attr: "int", atk: "Ranged", roles: ["Support","Disabler","Nuker"] },
  { id: 69, name: "Doom", attr: "str", atk: "Melee", roles: ["Carry","Disabler","Initiator","Durable","Nuker"] },
  { id: 70, name: "Ursa", attr: "agi", atk: "Melee", roles: ["Carry","Durable","Disabler"] },
  { id: 71, name: "Spirit Breaker", attr: "str", atk: "Melee", roles: ["Carry","Initiator","Disabler","Durable","Escape"] },
  { id: 72, name: "Gyrocopter", attr: "agi", atk: "Ranged", roles: ["Carry","Nuker","Disabler"] },
  { id: 73, name: "Alchemist", attr: "str", atk: "Melee", roles: ["Carry","Support","Durable","Disabler","Initiator","Nuker"] },
  { id: 74, name: "Invoker", attr: "int", atk: "Ranged", roles: ["Carry","Nuker","Disabler","Escape","Pusher"] },
  { id: 75, name: "Silencer", attr: "int", atk: "Ranged", roles: ["Carry","Support","Disabler","Initiator","Nuker"] },
  { id: 76, name: "Outworld Destroyer", attr: "int", atk: "Ranged", roles: ["Carry","Nuker","Disabler"] },
  { id: 77, name: "Lycan", attr: "str", atk: "Melee", roles: ["Carry","Pusher","Durable","Escape"] },
  { id: 78, name: "Brewmaster", attr: "all", atk: "Melee", roles: ["Carry","Initiator","Durable","Disabler","Nuker"] },
  { id: 79, name: "Shadow Demon", attr: "int", atk: "Ranged", roles: ["Support","Disabler","Initiator","Nuker"] },
  { id: 80, name: "Lone Druid", attr: "agi", atk: "Ranged", roles: ["Carry","Pusher","Durable"] },
  { id: 81, name: "Chaos Knight", attr: "str", atk: "Melee", roles: ["Carry","Disabler","Durable","Pusher","Initiator"] },
  { id: 82, name: "Meepo", attr: "agi", atk: "Melee", roles: ["Carry","Escape","Nuker","Disabler","Initiator","Pusher"] },
  { id: 83, name: "Treant Protector", attr: "str", atk: "Melee", roles: ["Support","Initiator","Durable","Disabler","Escape"] },
  { id: 84, name: "Ogre Magi", attr: "str", atk: "Melee", roles: ["Support","Nuker","Disabler","Durable","Initiator"] },
  { id: 85, name: "Undying", attr: "str", atk: "Melee", roles: ["Support","Durable","Disabler","Nuker"] },
  { id: 86, name: "Rubick", attr: "int", atk: "Ranged", roles: ["Support","Disabler","Nuker"] },
  { id: 87, name: "Disruptor", attr: "int", atk: "Ranged", roles: ["Support","Disabler","Nuker","Initiator"] },
  { id: 88, name: "Nyx Assassin", attr: "all", atk: "Melee", roles: ["Disabler","Nuker","Initiator","Escape"] },
  { id: 89, name: "Naga Siren", attr: "agi", atk: "Melee", roles: ["Carry","Support","Pusher","Disabler","Initiator","Escape"] },
  { id: 90, name: "Keeper of the Light", attr: "int", atk: "Ranged", roles: ["Support","Nuker","Disabler"] },
  { id: 91, name: "Io", attr: "all", atk: "Ranged", roles: ["Support","Escape","Nuker"] },
  { id: 92, name: "Visage", attr: "all", atk: "Ranged", roles: ["Support","Nuker","Durable","Disabler","Pusher"] },
  { id: 93, name: "Slark", attr: "agi", atk: "Melee", roles: ["Carry","Escape","Disabler","Nuker"] },
  { id: 94, name: "Medusa", attr: "agi", atk: "Ranged", roles: ["Carry","Disabler","Durable"] },
  { id: 95, name: "Troll Warlord", attr: "agi", atk: "Ranged", roles: ["Carry","Pusher","Disabler","Durable"] },
  { id: 96, name: "Centaur Warrunner", attr: "str", atk: "Melee", roles: ["Durable","Initiator","Disabler","Nuker","Escape"] },
  { id: 97, name: "Magnus", attr: "all", atk: "Melee", roles: ["Initiator","Disabler","Nuker","Escape"] },
  { id: 98, name: "Timbersaw", attr: "str", atk: "Melee", roles: ["Nuker","Durable","Escape"] },
  { id: 99, name: "Bristleback", attr: "str", atk: "Melee", roles: ["Carry","Durable","Initiator","Nuker"] },
  { id: 100, name: "Tusk", attr: "str", atk: "Melee", roles: ["Initiator","Disabler","Nuker"] },
  { id: 101, name: "Skywrath Mage", attr: "int", atk: "Ranged", roles: ["Support","Nuker","Disabler"] },
  { id: 102, name: "Abaddon", attr: "all", atk: "Melee", roles: ["Support","Carry","Durable"] },
  { id: 103, name: "Elder Titan", attr: "str", atk: "Melee", roles: ["Initiator","Disabler","Nuker","Durable"] },
  { id: 104, name: "Legion Commander", attr: "str", atk: "Melee", roles: ["Carry","Disabler","Initiator","Durable","Nuker"] },
  { id: 105, name: "Techies", attr: "all", atk: "Ranged", roles: ["Nuker","Disabler"] },
  { id: 106, name: "Ember Spirit", attr: "agi", atk: "Melee", roles: ["Carry","Escape","Nuker","Disabler","Initiator"] },
  { id: 107, name: "Earth Spirit", attr: "str", atk: "Melee", roles: ["Nuker","Escape","Disabler","Initiator","Durable"] },
  { id: 108, name: "Underlord", attr: "str", atk: "Melee", roles: ["Support","Nuker","Disabler","Durable","Escape"] },
  { id: 109, name: "Terrorblade", attr: "agi", atk: "Melee", roles: ["Carry","Pusher","Nuker"] },
  { id: 110, name: "Phoenix", attr: "str", atk: "Ranged", roles: ["Support","Nuker","Initiator","Escape","Disabler"] },
  { id: 111, name: "Oracle", attr: "int", atk: "Ranged", roles: ["Support","Nuker","Disabler","Escape"] },
  { id: 112, name: "Winter Wyvern", attr: "int", atk: "Ranged", roles: ["Support","Disabler","Nuker"] },
  { id: 113, name: "Arc Warden", attr: "all", atk: "Ranged", roles: ["Carry","Escape","Nuker"] },
  { id: 114, name: "Monkey King", attr: "agi", atk: "Melee", roles: ["Carry","Escape","Disabler","Initiator"] },
  { id: 119, name: "Dark Willow", attr: "int", atk: "Ranged", roles: ["Support","Nuker","Disabler","Escape"] },
  { id: 120, name: "Pangolier", attr: "all", atk: "Melee", roles: ["Carry","Nuker","Disabler","Durable","Escape","Initiator"] },
  { id: 121, name: "Grimstroke", attr: "int", atk: "Ranged", roles: ["Support","Nuker","Disabler","Escape"] },
  { id: 123, name: "Hoodwink", attr: "agi", atk: "Ranged", roles: ["Support","Nuker","Escape","Disabler"] },
  { id: 126, name: "Void Spirit", attr: "all", atk: "Melee", roles: ["Carry","Escape","Nuker","Disabler"] },
  { id: 128, name: "Snapfire", attr: "all", atk: "Ranged", roles: ["Support","Nuker","Disabler","Escape"] },
  { id: 129, name: "Mars", attr: "str", atk: "Melee", roles: ["Carry","Initiator","Disabler","Durable"] },
  { id: 131, name: "Ringmaster", attr: "int", atk: "Ranged", roles: ["Support","Nuker","Escape","Disabler"] },
  { id: 135, name: "Dawnbreaker", attr: "str", atk: "Melee", roles: ["Carry","Durable"] },
  { id: 136, name: "Marci", attr: "all", atk: "Melee", roles: ["Support","Carry","Initiator","Disabler","Escape"] },
  { id: 137, name: "Primal Beast", attr: "str", atk: "Melee", roles: ["Initiator","Durable","Disabler"] },
  { id: 138, name: "Muerta", attr: "int", atk: "Ranged", roles: ["Carry","Nuker","Disabler"] },
  { id: 145, name: "Kez", attr: "agi", atk: "Melee", roles: ["Carry","Escape","Disabler"] },
  { id: 155, name: "Largo", attr: "str", atk: "Melee", roles: ["Durable","Disabler","Support"] }
];

function findHeroByName(name) {
  if (!name) return null;
  var q = String(name).toLowerCase().trim();
  for (var i = 0; i < BRAIN_HEROES.length; i++) if (BRAIN_HEROES[i].name.toLowerCase() === q) return BRAIN_HEROES[i];
  for (var j = 0; j < BRAIN_HEROES.length; j++) if (BRAIN_HEROES[j].name.toLowerCase().indexOf(q) >= 0) return BRAIN_HEROES[j];
  return null;
}

function getHeroesByAttr(a) {
  var r = [];
  for (var i = 0; i < BRAIN_HEROES.length; i++) if (BRAIN_HEROES[i].attr === a) r.push(BRAIN_HEROES[i]);
  return r;
}

function getHeroesByRole(role) {
  var r = [];
  for (var i = 0; i < BRAIN_HEROES.length; i++) {
    for (var j = 0; j < BRAIN_HEROES[i].roles.length; j++) {
      if (BRAIN_HEROES[i].roles[j].toLowerCase() === role.toLowerCase()) { r.push(BRAIN_HEROES[i]); break; }
    }
  }
  return r;
}
