(function () {
"use strict";

var HEROES_FALLBACK = [
{ id: 1, name: "Anti-Mage", slug: "antimage" }, { id: 2, name: "Axe", slug: "axe" },
{ id: 3, name: "Bane", slug: "bane" }, { id: 4, name: "Bloodseeker", slug: "bloodseeker" },
{ id: 5, name: "Crystal Maiden", slug: "crystal_maiden" }, { id: 6, name: "Drow Ranger", slug: "drow_ranger" },
{ id: 7, name: "Earthshaker", slug: "earthshaker" }, { id: 8, name: "Juggernaut", slug: "juggernaut" },
{ id: 9, name: "Mirana", slug: "mirana" }, { id: 10, name: "Morphling", slug: "morphling" },
{ id: 11, name: "Shadow Fiend", slug: "nevermore" }, { id: 12, name: "Phantom Lancer", slug: "phantom_lancer" },
{ id: 13, name: "Puck", slug: "puck" }, { id: 14, name: "Pudge", slug: "pudge" },
{ id: 15, name: "Razor", slug: "razor" }, { id: 16, name: "Sand King", slug: "sand_king" },
{ id: 17, name: "Storm Spirit", slug: "storm_spirit" }, { id: 18, name: "Sven", slug: "sven" },
{ id: 19, name: "Tiny", slug: "tiny" }, { id: 20, name: "Vengeful Spirit", slug: "vengefulspirit" },
{ id: 21, name: "Windranger", slug: "windrunner" }, { id: 22, name: "Zeus", slug: "zuus" },
{ id: 23, name: "Kunkka", slug: "kunkka" }, { id: 25, name: "Lina", slug: "lina" },
{ id: 26, name: "Lion", slug: "lion" }, { id: 27, name: "Shadow Shaman", slug: "shadow_shaman" },
{ id: 28, name: "Slardar", slug: "slardar" }, { id: 29, name: "Tidehunter", slug: "tidehunter" },
{ id: 30, name: "Witch Doctor", slug: "witch_doctor" }, { id: 31, name: "Lich", slug: "lich" },
{ id: 32, name: "Riki", slug: "riki" }, { id: 33, name: "Enigma", slug: "enigma" },
{ id: 34, name: "Tinker", slug: "tinker" }, { id: 35, name: "Sniper", slug: "sniper" },
{ id: 36, name: "Necrophos", slug: "necrolyte" }, { id: 37, name: "Warlock", slug: "warlock" },
{ id: 38, name: "Beastmaster", slug: "beastmaster" }, { id: 39, name: "Queen of Pain", slug: "queenofpain" },
{ id: 40, name: "Venomancer", slug: "venomancer" }, { id: 41, name: "Faceless Void", slug: "faceless_void" },
{ id: 42, name: "Wraith King", slug: "skeleton_king" }, { id: 43, name: "Death Prophet", slug: "death_prophet" },
{ id: 44, name: "Phantom Assassin", slug: "phantom_assassin" }, { id: 45, name: "Pugna", slug: "pugna" },
{ id: 46, name: "Templar Assassin", slug: "templar_assassin" }, { id: 47, name: "Viper", slug: "viper" },
{ id: 48, name: "Luna", slug: "luna" }, { id: 49, name: "Dragon Knight", slug: "dragon_knight" },
{ id: 50, name: "Dazzle", slug: "dazzle" }, { id: 51, name: "Clockwerk", slug: "rattletrap" },
{ id: 52, name: "Leshrac", slug: "leshrac" }, { id: 53, name: "Nature's Prophet", slug: "furion" },
{ id: 54, name: "Lifestealer", slug: "life_stealer" }, { id: 55, name: "Dark Seer", slug: "dark_seer" },
{ id: 56, name: "Clinkz", slug: "clinkz" }, { id: 57, name: "Omniknight", slug: "omniknight" },
{ id: 58, name: "Enchantress", slug: "enchantress" }, { id: 59, name: "Huskar", slug: "huskar" },
{ id: 60, name: "Night Stalker", slug: "night_stalker" }, { id: 61, name: "Broodmother", slug: "broodmother" },
{ id: 62, name: "Bounty Hunter", slug: "bounty_hunter" }, { id: 63, name: "Weaver", slug: "weaver" },
{ id: 64, name: "Jakiro", slug: "jakiro" }, { id: 65, name: "Batrider", slug: "batrider" },
{ id: 66, name: "Chen", slug: "chen" }, { id: 67, name: "Spectre", slug: "spectre" },
{ id: 68, name: "Ancient Apparition", slug: "ancient_apparition" }, { id: 69, name: "Doom", slug: "doom_bringer" },
{ id: 70, name: "Ursa", slug: "ursa" }, { id: 71, name: "Spirit Breaker", slug: "spirit_breaker" },
{ id: 72, name: "Gyrocopter", slug: "gyrocopter" }, { id: 73, name: "Alchemist", slug: "alchemist" },
{ id: 74, name: "Invoker", slug: "invoker" }, { id: 75, name: "Silencer", slug: "silencer" },
{ id: 76, name: "Outworld Destroyer", slug: "obsidian_destroyer" }, { id: 77, name: "Lycan", slug: "lycan" },
{ id: 78, name: "Brewmaster", slug: "brewmaster" }, { id: 79, name: "Shadow Demon", slug: "shadow_demon" },
{ id: 80, name: "Lone Druid", slug: "lone_druid" }, { id: 81, name: "Chaos Knight", slug: "chaos_knight" },
{ id: 82, name: "Meepo", slug: "meepo" }, { id: 83, name: "Treant Protector", slug: "treant" },
{ id: 84, name: "Ogre Magi", slug: "ogre_magi" }, { id: 85, name: "Undying", slug: "undying" },
{ id: 86, name: "Rubick", slug: "rubick" }, { id: 87, name: "Disruptor", slug: "disruptor" },
{ id: 88, name: "Nyx Assassin", slug: "nyx_assassin" }, { id: 89, name: "Naga Siren", slug: "naga_siren" },
{ id: 90, name: "Keeper of the Light", slug: "keeper_of_the_light" }, { id: 91, name: "Io", slug: "wisp" },
{ id: 92, name: "Visage", slug: "visage" }, { id: 93, name: "Slark", slug: "slark" },
{ id: 94, name: "Medusa", slug: "medusa" }, { id: 95, name: "Troll Warlord", slug: "troll_warlord" },
{ id: 96, name: "Centaur Warrunner", slug: "centaur" }, { id: 97, name: "Magnus", slug: "magnataur" },
{ id: 98, name: "Timbersaw", slug: "shredder" }, { id: 99, name: "Bristleback", slug: "bristleback" },
{ id: 100, name: "Tusk", slug: "tusk" }, { id: 101, name: "Skywrath Mage", slug: "skywrath_mage" },
{ id: 102, name: "Abaddon", slug: "abaddon" }, { id: 103, name: "Elder Titan", slug: "elder_titan" },
{ id: 104, name: "Legion Commander", slug: "legion_commander" }, { id: 105, name: "Techies", slug: "techies" },
{ id: 106, name: "Ember Spirit", slug: "ember_spirit" }, { id: 107, name: "Earth Spirit", slug: "earth_spirit" },
{ id: 108, name: "Underlord", slug: "abyssal_underlord" }, { id: 109, name: "Terrorblade", slug: "terrorblade" },
{ id: 110, name: "Phoenix", slug: "phoenix" }, { id: 111, name: "Oracle", slug: "oracle" },
{ id: 112, name: "Winter Wyvern", slug: "winter_wyvern" }, { id: 113, name: "Arc Warden", slug: "arc_warden" },
{ id: 114, name: "Monkey King", slug: "monkey_king" }, { id: 119, name: "Dark Willow", slug: "dark_willow" },
{ id: 120, name: "Pangolier", slug: "pangolier" }, { id: 121, name: "Grimstroke", slug: "grimstroke" },
{ id: 123, name: "Hoodwink", slug: "hoodwink" }, { id: 126, name: "Void Spirit", slug: "void_spirit" },
{ id: 128, name: "Snapfire", slug: "snapfire" }, { id: 129, name: "Mars", slug: "mars" },
{ id: 131, name: "Dawnbreaker", slug: "dawnbreaker" }, { id: 136, name: "Marci", slug: "marci" },
{ id: 137, name: "Primal Beast", slug: "primal_beast" }, { id: 138, name: "Muerta", slug: "muerta" },
{ id: 145, name: "Kez", slug: "kez" }, { id: 155, name: "Largo", slug: "largo" }
];

var ITEMS_FALLBACK = {
1: ["Blink Dagger", "blink"], 29: ["Boots of Speed", "boots"], 36: ["Magic Wand", "magic_wand"],
63: ["Power Treads", "power_treads"], 79: ["Aghanim's Scepter", "ultimate_scepter"],
96: ["Scythe of Vyse", "sheepstick"], 108: ["Aghanim's Shard", "aghanims_shard"],
116: ["Black King Bar", "black_king_bar"], 119: ["Force Staff", "force_staff"],
127: ["Blade Mail", "blade_mail"], 145: ["Battle Fury", "bfury"], 147: ["Manta Style", "manta"],
154: ["Abyssal Blade", "abyssal_blade"], 160: ["Radiance", "radiance"], 174: ["Diffusal Blade", "diffusal_blade"],
206: ["Ethereal Blade", "ethereal_blade"], 208: ["Eye of Skadi", "skadi"], 212: ["Heart of Tarrasque", "heart"],
235: ["Octarine Core", "octarine_core"], 236: ["Dragon Lance", "dragon_lance"], 249: ["Silver Edge", "silver_edge"],
250: ["Sange and Yasha", "sange_and_yasha"], 254: ["Glimmer Cape", "glimmer_cape"], 263: ["Hurricane Pike", "hurricane_pike"],
266: ["Spirit Vessel", "spirit_vessel"], 273: ["Aeon Disk", "aeon_disk"], 277: ["Shiva's Guard", "shivas_guard"],
597: ["Eternal Shroud", "eternal_shroud"], 603: ["Overwhelming Blink", "overwhelming_blink"],
604: ["Swift Blink", "swift_blink"], 605: ["Arcane Blink", "arcane_blink"],
607: ["Fallen Sky", "fallen_sky"], 608: ["Pirate Hat", "pirate_hat"], 609: ["Dandelion Amulet", "dandelion_amulet"],
610: ["Telescope", "telescope"], 611: ["Magic Lamp", "magic_lamp"],
1123: ["Rattlecage", "rattlecage"], 1124: ["Witless Shako", "witless_shako"]
};

var ALIASES = {
"жугер":"Juggernaut","пудж":"Pudge","инвокер":"Invoker","сф":"Shadow Fiend",
"ам":"Anti-Mage","антимаг":"Anti-Mage","па":"Phantom Assassin","фантомка":"Phantom Assassin",
"сларк":"Slark","шторм":"Storm Spirit","зевс":"Zeus","лина":"Lina",
"дров":"Drow Ranger","снайпер":"Sniper","свен":"Sven","ц
